# CCS Limpieza de Datos

En esta seccion se hara la limpieza de los dato ya explorados inicialmente, con el fin de limpiar nulos, eliminar duplicados y corregir tipos de datos

In [111]:
# Import Libraries

import pandas as pd
import numpy as np

In [112]:
# Import data

df_fv = pd.read_csv('./data_source/data_query_for_fac_ventas.csv')

In [113]:
df_fv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7701 entries, 0 to 7700
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   NUMERO_DE_IDENTIFICACION  7701 non-null   int64
 1   PRIMER_APELLIDO           7701 non-null   object
 2   SEGUNDO_APELLIDO          7566 non-null   object
 3   PRIMER_NOMBRE             7701 non-null   object
 4   SEGUNDO_NOMBRE            7328 non-null   object
 5   CURSO                     7700 non-null   object
 6   PRECIO_NETO               7701 non-null   float64
 7   FECHA_DE_PAGO             7701 non-null   object
 8   RENOVACION                7468 non-null   object
 9   FECHA_DE_VENTA            7701 non-null   object
 10  PROFESION                 5905 non-null   object
 11  GENERO                    5802 non-null   object
 12  FECHA_DE_NACIMIENTO       7698 non-null   object
 13  CIUDAD_REGION             7527 non-null   object
 14  MODALIDAD                 7178 non-null   object
 15  PROCEDENCIA               7205 non-null   object
 16  MEDIO_DE_PAGO             6912 non-null   object
 17  RESPONSABLE_VENTA         7637 non-null   object
 18  elaboro                   7492 non-null   object
dtypes: float64(1), int64(1), object(17)
memory usage: 1.1+ MB

In [114]:
# Null values per column

df_fv.isnull().sum()

NUMERO_DE_IDENTIFICACION       0
PRIMER_APELLIDO                0
SEGUNDO_APELLIDO             135
PRIMER_NOMBRE                  0
SEGUNDO_NOMBRE               373
CURSO                          1
PRECIO_NETO                    0
FECHA_DE_PAGO                  0
RENOVACION                   233
FECHA_DE_VENTA                 0
PROFESION                   1796
GENERO                      1899
FECHA_DE_NACIMIENTO            3
CIUDAD_REGION                174
MODALIDAD                    523
PROCEDENCIA                  496
MEDIO_DE_PAGO                789
RESPONSABLE_VENTA             64
elaboro                      209
dtype: int64

## 1. Limpieza de datos nulos en columnas que no pueden tener datos nulos

Como se menciono en la seccion de entendimiento de los datos, existe ciertas columnas que no pueden tener datos nulos debido al funcionamientos del negocio,
"CURSO" es una de estas filas y se va a tratar como se indica a continuacion.

In [115]:
# Null percentage on COURSE regarding of total of COURSE registers
'''
Since the CURSOS column cannot contain null values, we evaluated which percentage of the total is represented by a single record.  
It is 0.01%, so we have decided to remove this row from the DataFrame.

'''

per_null = (df_fv["CURSO"].isnull().sum() / df_fv["CURSO"].value_counts().sum()) * 100
per_null

np.float64(0.012987012987012988)

In [116]:
# remove a single row from the DataFrame for null value on CURSOS

df_fv.dropna(subset=['CURSO'], inplace=True)

In [117]:
df_fv.shape

(7700, 19)

## 2. Manejo de datos nulos en columas que pueden tener datos nulos

En las columnas que si pueden tener datos nulos se va a dar un manejo para que no tenga como un dato nulo sino un valor estandar que sera "UNKNOWN" para datos categoricos y la media de los valores para datos numericos

In [118]:
# Action to fill each categorical column with a normaliced text "UNKNOWN"

col_list = [
 'SEGUNDO_APELLIDO',
 'SEGUNDO_NOMBRE',
 'RENOVACION',
 'PROFESION',
 'GENERO',
 'CIUDAD_REGION',
 'MODALIDAD',
 'PROCEDENCIA',
 'MEDIO_DE_PAGO',
 'RESPONSABLE_VENTA',
 'elaboro'
]

for col in col_list:
    df_fv.loc[df_fv[col].isnull(), col] = 'UNKNOWN'

In [119]:
df_fv[df_fv['FECHA_DE_NACIMIENTO'].isna()]

,NUMERO_DE_IDENTIFICACION,PRIMER_APELLIDO,SEGUNDO_APELLIDO,PRIMER_NOMBRE,SEGUNDO_NOMBRE,CURSO,PRECIO_NETO,FECHA_DE_PAGO,RENOVACION,FECHA_DE_VENTA,PROFESION,GENERO,FECHA_DE_NACIMIENTO,CIUDAD_REGION,MODALIDAD,PROCEDENCIA,MEDIO_DE_PAGO,RESPONSABLE_VENTA,elaboro
6136,1004534712,Tupaz,Ceballos,Jonatan,Herney,Bls,30000.0,2026-01-10,No,2026-01-01,Auxiliar de enfermería,Masculino,NaN,Pasto - Nariño,Actualizacion,Facebook,Nequi,Ccs,Sebastian Rosero Patiño
6137,1004534712,Tupaz,Ceballos,Jonatan,Herney,Admon de medicamentos,30000.0,2026-01-10,No,2026-01-01,Auxiliar de enfermería,Masculino,NaN,Pasto - Nariño,Actualizacion,Facebook,Nequi,Ccs,Sebastian Rosero Patiño
6358,1004534712,Tupaz,Ceballos,Jonatan,Herney,Toma de muestras,30000.0,2026-01-14,No,2026-01-01,Auxiliar de enfermería,Masculino,NaN,Pasto - Nariño,Actualizacion,Facebook,Nequi,Ccs,Sebastian Rosero Patiño

In [120]:
# Action to change default dates '1900-01-01' by NaT
# Tis is not a representative value for the general analysis so will leave as NaT
values = ["1900-01-01"]

df_fv.loc[df_fv['FECHA_DE_NACIMIENTO'].isin(values), 'FECHA_DE_NACIMIENTO'] = np.nan

In [121]:
df_fv.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7700 entries, 0 to 7700
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   NUMERO_DE_IDENTIFICACION  7700 non-null   int64
 1   PRIMER_APELLIDO           7700 non-null   object
 2   SEGUNDO_APELLIDO          7700 non-null   object
 3   PRIMER_NOMBRE             7700 non-null   object
 4   SEGUNDO_NOMBRE            7700 non-null   object
 5   CURSO                     7700 non-null   object
 6   PRECIO_NETO               7700 non-null   float64
 7   FECHA_DE_PAGO             7700 non-null   object
 8   RENOVACION                7700 non-null   object
 9   FECHA_DE_VENTA            7700 non-null   object
 10  PROFESION                 7700 non-null   object
 11  GENERO                    7700 non-null   object
 12  FECHA_DE_NACIMIENTO       5233 non-null   object
 13  CIUDAD_REGION             7700 non-null   object
 14  MODALIDAD                 7700 non-null   object
 15  PROCEDENCIA               7700 non-null   object
 16  MEDIO_DE_PAGO             7700 non-null   object
 17  RESPONSABLE_VENTA         7700 non-null   object
 18  elaboro                   7700 non-null   object
dtypes: float64(1), int64(1), object(17)
memory usage: 1.2+ MB

In [122]:
# Now we will normalice column names to uppercase

df_fv.columns = df_fv.columns.str.upper()

In [123]:
df_fv.sample(2)

,NUMERO_DE_IDENTIFICACION,PRIMER_APELLIDO,SEGUNDO_APELLIDO,PRIMER_NOMBRE,SEGUNDO_NOMBRE,CURSO,PRECIO_NETO,FECHA_DE_PAGO,RENOVACION,FECHA_DE_VENTA,PROFESION,GENERO,FECHA_DE_NACIMIENTO,CIUDAD_REGION,MODALIDAD,PROCEDENCIA,MEDIO_DE_PAGO,RESPONSABLE_VENTA,ELABORO
763,38558508,Muñoz,Gomez,Maria,Antonieta,Duelo,0.0,2024-02-01,No,2024-02-01,Jefe de enfermería,Femenino,NaN,Pasto - Nariño,Virtual asincrónica,Facebook,Obsequio,Pasto Salud,Sebastian Rosero Patiño
7433,1087782218,Estupiñan,Caicedo,Gina,Nathalia,Iami,25000.0,2026-05-15,Si,2026-05-01,UNKNOWN,UNKNOWN,NaN,Pasto - Nariño,UNKNOWN,UNKNOWN,Nequi,Ccs,UNKNOWN

## 3. Correccion de el tipo de dato

En este paso vamos a corregir el tipo de dato asignado a cada variable de DataFrame

In [124]:
data_type = {
    'numeric' : ['PRECIO_NETO'],
    'category' : [
        'NUMERO_DE_IDENTIFICACION',
        'CURSO',
        'RENOVACION',
        'PROFESION',
        'GENERO',
        'CIUDAD_REGION',
        'MODALIDAD',
        'PROCEDENCIA',
        'MEDIO_DE_PAGO',
        'RESPONSABLE_VENTA'
        ],
    'date' : [
        'FECHA_DE_PAGO',
        'FECHA_DE_VENTA',
        'FECHA_DE_NACIMIENTO'
        ]
}

In [125]:
def change_dtype(df, key, value):
    if key == 'numeric':
        for col in value:
            df[col] = pd.to_numeric(df[col], errors='coerce')
            print("Numeric type changed!")
    elif key == 'category':
        for col in value:
            df[col] = df[col].astype('category')
            print("Category type changed!")
    elif key == 'date':
        for col in value:
            df[col] = pd.to_datetime(df[col], errors='coerce')
            print("Date type changed!")
    else:
        print("ERROR!")

In [126]:
for key, value in data_type.items():
    change_dtype(df_fv, key, value)

Numeric type changed!
Category type changed!
Category type changed!
Category type changed!
Category type changed!
Category type changed!
Category type changed!
Category type changed!
Category type changed!
Category type changed!
Category type changed!
Date type changed!
Date type changed!
Date type changed!

In [127]:
df_fv.dtypes

NUMERO_DE_IDENTIFICACION          category
PRIMER_APELLIDO                     object
SEGUNDO_APELLIDO                    object
PRIMER_NOMBRE                       object
SEGUNDO_NOMBRE                      object
CURSO                             category
PRECIO_NETO                        float64
FECHA_DE_PAGO               datetime64[ns]
RENOVACION                        category
FECHA_DE_VENTA              datetime64[ns]
PROFESION                         category
GENERO                            category
FECHA_DE_NACIMIENTO         datetime64[ns]
CIUDAD_REGION                     category
MODALIDAD                         category
PROCEDENCIA                       category
MEDIO_DE_PAGO                     category
RESPONSABLE_VENTA                 category
ELABORO                             object
dtype: object

In [128]:
df_fv.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7700 entries, 0 to 7700
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   NUMERO_DE_IDENTIFICACION  7700 non-null   category
 1   PRIMER_APELLIDO           7700 non-null   object
 2   SEGUNDO_APELLIDO          7700 non-null   object
 3   PRIMER_NOMBRE             7700 non-null   object
 4   SEGUNDO_NOMBRE            7700 non-null   object
 5   CURSO                     7700 non-null   category
 6   PRECIO_NETO               7700 non-null   float64
 7   FECHA_DE_PAGO             7700 non-null   datetime64[ns]
 8   RENOVACION                7700 non-null   category
 9   FECHA_DE_VENTA            7700 non-null   datetime64[ns]
 10  PROFESION                 7700 non-null   category
 11  GENERO                    7700 non-null   category
 12  FECHA_DE_NACIMIENTO       5222 non-null   datetime64[ns]
 13  CIUDAD_REGION             7700 non-null   category
 14  MODALIDAD                 7700 non-null   category
 15  PROCEDENCIA               7700 non-null   category
 16  MEDIO_DE_PAGO             7700 non-null   category
 17  RESPONSABLE_VENTA         7700 non-null   category
 18  ELABORO                   7700 non-null   object
dtypes: category(10), datetime64[ns](3), float64(1), object(5)
memory usage: 780.4+ KB

## 4. Creacion de columnas derivadas

In [129]:
# Age columns

today = pd.Timestamp.today()

df_fv['EDAD'] = (today.year - df_fv['FECHA_DE_NACIMIENTO'].dt.year)

In [130]:
# Year of Sale

df_fv['ANIO_VENTA'] = df_fv['FECHA_DE_PAGO'].dt.year

In [131]:
# Month of Sale

df_fv['MES_VENTA'] = df_fv['FECHA_DE_PAGO'].dt.month_name(locale="es_ES")

In [ ]:
# Define Cleint Ranges
'''
MENOR -> 0 - 18
JOVEN -> 18 - 30
ADULTO -> 30 - 50
SENIOR -> 50 -120
'''

bins = [0, 18, 30, 50, 120]
labels = ["Menor", "Joven", "Adulto", "Senior"]

df_fv['GRUPO_EDAD'] = pd.cut(df_fv['EDAD'], bins= bins, labels=labels)

In [142]:
df_fv.sample(5)

,NUMERO_DE_IDENTIFICACION,PRIMER_APELLIDO,SEGUNDO_APELLIDO,PRIMER_NOMBRE,SEGUNDO_NOMBRE,CURSO,PRECIO_NETO,FECHA_DE_PAGO,RENOVACION,FECHA_DE_VENTA,...,CIUDAD_REGION,MODALIDAD,PROCEDENCIA,MEDIO_DE_PAGO,RESPONSABLE_VENTA,ELABORO,EDAD,ANIO_VENTA,MES_VENTA,GRUPO_EDAD
3884,98378748,Caicedo,Guerrero,Jorge,Julio,Manejo defensivo,70000.0,2025-07-28,No,2025-07-01,...,Pasto - Nariño,Capacitación,Facebook,Caja,Ccs,Juan Camilo Urbano Paredes,56.0,2025,Julio,Senior
591,1084846415,Mitis,Rivera,Yuli,Katerine,Bls,32000.0,2024-12-26,No,2024-12-01,...,Pasto - Nariño,Actualizacion,Facebook,Efecty,Ccs,Juan Camilo Urbano Paredes,38.0,2024,Diciembre,Adulto
6330,36993965,Montenegro,De ruiz,Rita,Guadalupe,Paliativos,30000.0,2026-01-14,No,2026-01-01,...,Pasto - Nariño,Actualizacion,Facebook,Nequi,Ccs,Sebastian Rosero Patiño,70.0,2026,Enero,Senior
2195,1085338527,Ortiz,Meneses,Steven,Rodrigo,Químicos,35000.0,2025-04-09,No,2025-04-01,...,Pasto - Nariño,Actualizacion,Facebook,Nequi,H. San Pedro,Juan Camilo Urbano Paredes,29.0,2025,Abril,Joven
6507,1192766836,Navarro,Velasquez,David,Esteban,Acls,90000.0,2026-06-01,Si,2026-06-02,...,Pasto - Nariño,Virtual asincrónica,Alianzas comerciales,Nequi,Ccs,Sebastian Rosero Patiño,25.0,2026,Junio,Joven

In [143]:
df_fv['GRUPO_EDAD'].value_counts()

GRUPO_EDAD
Adulto    2952
Joven     1816
Senior     405
Menor       28
Name: count, dtype: int64